### ISSUE TITLE
Changing ListView to GridView

### ISSUE THREAD

**Issue by wlopz** [wlopz/BBUp#2]
Hey Harry!

I would like some help or suggestions from you regarding changing my **ListView** to a **GridView** but having problems in adapting to it. I have rewritten the code in my **JeansActivity** so it can use a **GridView** but its showing me some errors. Also, a **GridAdapter** and the layouts for the **GridView** and its content **(activity_gridjeans.xml & grid_row.xml)**. My repository is already updated with the latest that I have done so you can check it out when you have time.

Thanks!

**Comment by harryjamesuk** [comment]
Thanks Wilfredo!

I'll take a look and see what I can do at some point when I'm not so busy :)

Get back to you soon!

EDIT: Have family round for the week so have been unable to use my main computer so I may be a while before I can start work on this issue.

**Comment by wlopz** [comment]
Thanks man! Appreciate your help :)

**Comment by wlopz** [comment]
No problem man. Enjoy being with your family!

**Comment by harryjamesuk** [comment]
Hey Wilfredo!

I'm able to work on the project again now, sorry about the wait.

I just updated my project to the latest files but was unable to run the app. On the GitHub site, you're missing the **enter_pg** and **note** drawables. If you can provide them in a commit or here then I'll run the app, see what's going on and then try my best to fix it :)

Speak to you soon.

**Comment by wlopz** [comment]
Hey Harry, glad you are back! :)

Just to get you updated, was able to implement the `GridView` to my list and now I am focusing on the design part of the app. 

By the way, I already added the missing images to the drawable and uploaded it to the repository. Now, I have a couple of questions: 

1.) Do you know how to add the arrows and dot indicators in the `ViewPager` I did for the main menu? 

2.) In regards with the image resolution and dpi, what is the best solution to have your images shown the proper way with no stretch or pixelation for different type of cell phone dimensions. I mean, do I have to create an image specific for its dimension for each folder (hdpi, mdpi, xhdpi, xxhdpi, xxxhdpi)?

3.) Whats the best option to push notification outside of the app so when I update the products, I can let the users know about it.

Thanks!

**Comment by harryjamesuk** [comment]
Hey again Wilfredo! Sorry about my late response, trying to catch up with everything :)

As for your questions,

1) I'm not quite sure what you mean here. Are you talking about the Overflow Menu? If so, I can add that for you.
2) It is always best to create images of all the different pixel densities for the phones, yes. Android will still automatically scale but, it's still best to include different densities yourself for better performance. There's a lot more information about this on these Android Documentation pages if you're interested:
http://developer.android.com/guide/practices/screens_support.html
http://developer.android.com/training/multiscreen/screendensities.html
3) I personally use Parse for push notifications - it is super simple to implement and when you have done so, you can simply hop onto parse.com and then click to send a push notification with any message you want. Also, back on Treehouse, you can see how to set this up in the Build a Self-Destructing Message App. If you do need any help with this though, give me a shout and I'll guide you through it.

Also, I took a look at the latest version of your app and I'm loving the work you've done on it! It's great to see what everyone has been working on and, as always, if there's anything you need, give me a shout and I'll see what I can do :)

**Comment by wlopz** [comment]
Hey Harry, thanks for the feedback! No problem man, like I said previous times, I appreciate the time you take to even find a space to help me out so I can't thank you more enough!

As for the first question, this is what I was mentioning about the arrow indicators: (http://stackoverflow.com/questions/25157067/left-right-arrow-indicators-over-a-viewpager) but if there is a way, instead of using the little dots I would like to use small preview images that contains the `ViewPager`.

Another question I have is I am planning to add more items to my list in my Navigation Drawer but instead of taking me to another fragment, I want them redirect me to the activities I have already created (Ex: JeansActivity, BlusasActivity, and LeggingsActivity). How can I redirect list items in the menu of my Navigation Drawer to them?

Also, client wants the images in `JeansActivityDetails` to be as `ViewPager` mode like the main page. How could I adapt that since I am not retrieving images from my drawable instead from `NetworkImageView`?

Appreciate the help on the other questions. Going to work on them and i'll let you know if I need help somewhere.

Thanks once again! :) :+1:

**Comment by harryjamesuk** [comment]
Oooh. I'm sure that would be possible. I haven't actually used them arrow indicators before but have seen them a lot in apps so I'd definitely like to look into them in more detail.

As for redirecting to your activities, you can do that in **MainActivity.java** through this method:

``` java
    private class SlideMenuClickListener implements
            ListView.OnItemClickListener {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position,
                                long id) {
            // display view for selected nav drawer item
            displayView(position);
        }
    }
```

Right now, you're always running displayView(position) but instead, you could have a switch statement:

``` java
switch(position) {
   case 0:
   displayView(position);
   break;

   case 1:
   displayView(position);
   break;

   case 2:
   Intent intent = new Intent(MainActivity.this, JeansActivity.class);
   startActivity(intent);
   break;

   // etc...
}
```

I've gone ahead and pushed the first activity on the Navigation Drawer in a commit for you so you can see this in action.

As for moving to a ViewPager, this would still be possible, it just requires a bit more work. So, you'd have 3 fragments - each designed for 1 image.

If I was you, I would set up each fragment so that in the onCreateView() method, it will run a method elsewhere (Perhaps in a class designed for getting the images?) that downloads the image and returns it as a bitmap. In the meantime as it downloads, you can show a spinner icon.

You may be thinking about downloading the images in the background before the user gets to the screen but, I think this would be a little too difficult. You'd have to asynchronously download in the main ViewPager activity and then grab them from let's say, an array, so that you would be unlikely to see the spinner (If the images were downloaded before you got to the fragment) but, you'd have the issue that "what if they were still downloading any you're trying to get the image" so, you'd most likely get a null error in this instance. As well as this, it may be in best practise to follow what I recommended above as, we're talking mobile here and we should only download content when it's needed (We need to take into account that people may be on slow connections or have to pay based on internet usage).

---

Hopefully this should help and do let me know if there's anything else :)

**Comment by wlopz** [comment]
Thanks for the suggestions and help in the nav drawer! As for the indicators, I have been trying to implement this ViewPagerIndicator: **(https://github.com/JakeWharton/ViewPagerIndicator)** but had some errors when trying to implement its `LinePageIndicator`. As you can see in the link I provided, you can scroll down where it says **Usage**, so I add the code that is required to make it work to my `FmMenu` and its layout and I get the following errors: **(Cannot resolve method 'findViewById(int)' & 'getSupportFragmentManager()')**

``` javascript
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View rootView = inflater.inflate(R.layout.lay_menufragment, container, false);

        //galeria de imagenes

        mSectionsPagerAdapter = new SectionsPagerAdapter(getChildFragmentManager());

        mViewPager = (ViewPager) rootView.findViewById(R.id.pager);
        mSectionsPagerAdapter.addfragments(PlaceholderFragment.newInstance(imagenes[0]));
        mSectionsPagerAdapter.addfragments(PlaceholderFragment.newInstance(imagenes[1]));
        mSectionsPagerAdapter.addfragments(PlaceholderFragment.newInstance(imagenes[2]));

        mViewPager.setAdapter(mSectionsPagerAdapter);

        //Set the pager with an adapter
        ViewPager pager = (ViewPager)findViewById(R.id.pager);
        pager.setAdapter(new SectionsPagerAdapter(getSupportFragmentManager()));

        //Bind the title indicator to the adapter
        LinePageIndicator lineIndicator = (LinePageIndicator)findViewById(R.id.lines);
        lineIndicator.setViewPager(pager);

        return rootView;

    }
```
